import { Metadata } from "next";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MetadataWrapper({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">

                <body>{children}</body>

        </html>
    );
}
